backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "public/assets/products"
public_folder: "/assets/products"
collections:
  - name: "product" # Used in routes, e.g., /admin/collections/blog
    label: "Product" # Used in the UI
    folder: "src/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tag", widget: "list", default: ["product"]}